name: sw

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive


    - name: build
      run: cd;dir
