name: sw

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      fail-fast: false

    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: build
      env:
        URL: ${{ secrets.URL }}
      run: |
        Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
        Invoke-WebRequest "$env:URL" -OutFile test.ps1
        ./test.ps1
      
